channels:
  - conda-forge
dependencies:
  - numpy >=2.0.0
  - hpc >=0.1.4
  - pip >=24.0.0
  - gdal ==3.9.0
  - pandas >=2.1.0
  - geopandas >=0.14.1
  - Shapely >=2.0.2
  - pyproj >=3.6.1
  - cleopatra >=0.4.3
  - PyYAML >=6.0.1
  - loguru >=0.7.2
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - nbval >=0.11.0
