channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - hpc >=0.1.3
  - pip >=23.3.1
  - gdal ==3.8.4
  - pandas >=2.1.0
  - geopandas >=0.14.1
  - Shapely >=2.0.2
  - pyproj >=3.6.1
  - PyYAML >=6.0.1
  - loguru >=0.7.2
  - pytest >=7.4.3
  - pytest-cov >=4.1.0
