channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy ==1.23.5
  - pip >=22.3.1
  - gdal >=3.5.3
  - affine >=2.3.1
  - pandas >=1.4.4
  - geopandas >=0.12.2
  - Rtree >=1.0.0
  - Shapely >=1.8.4,<2
  - rasterio >=1.3.0
  - netCDF4 >=1.6.1
  - geopy >=2.2.0
  - pyproj >=3.4.0
  - loguru >=0.6.0
  - pytest >=7.2.0
  - pytest-cov ==4.0.0
  - requests >=2.28.1
