channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy >=1.24.1
  - hpc >=0.1.1
  - pip >=22.3.1
  - gdal >=3.6.2
  - pandas >=2.0.0
  - geopandas >=0.12.2
  - Shapely >=1.8.4,<2
  - pyproj >=3.4.0
  - PyYAML >=6.0
  - loguru >=0.6.0
  - pytest >=7.2.0
  - pytest-cov >=4.0.0
