channels:
  - conda-forge
dependencies:
  - numpy >=2.1.3
  - hpc >=0.1.4
  - pip >=24.3.1
  - gdal ==3.10.0
  - libgdal-netcdf ==3.10.0
  - libgdal-hdf4  ==3.10.0
  - pandas >=2.2.3
  - geopandas >=1.0.1
  - Shapely >=2.0.6
  - pyproj >=3.7.0
  - cleopatra >=0.5.1
  - PyYAML >=6.0.2
  - loguru >=0.7.2
  - pytest >=8.3.4
  - pytest-cov >=6.0.0
  - nbval >=0.11.0
