channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy >=1.24.1
  - hpc >=0.1.0
  - pip >=22.3.1
  - gdal >=3.5.3
  - pandas >=1.4.4
  - geopandas >=0.12.2
  - Shapely >=1.8.4,<2
#  - netCDF4 >=1.6.1
  - pyproj >=3.4.0
  - h3-py >=3.7.4
  - PyYAML >=6.0
  - loguru >=0.6.0
  - pytest >=7.2.0
  - pytest-cov >=4.0.0
