channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - hpc >=0.1.2
  - pip >=23.2.1
  - gdal >=3.7.0, <3.7.2
  - pandas >=2.0.0
  - geopandas >=0.13.2
  - Shapely >=2.0.1
  - pyproj >=3.6.0
  - cleopatra >=0.4.0
  - PyYAML >=6.0.1
  - loguru >=0.7.0
  - pytest >=7.4.0
  - pytest-cov >=4.1.0
