channels:
  - conda-forge
dependencies:
  - python >=3.9.0
  - pip >=21.3.1
  - matplotlib >=3.4.2,<3.6.0
  - numpy==1.20.*
  - numpydoc==1.1.0
  - typing-extensions==3.10.*
  - pip:
    - pydata-sphinx-theme
    - nbsphinx
