name: conda-deployment

on: [push]

jobs:
  Main-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          use-mamba: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true

      - name: Install dev-dependencies
        run: |
            pip install .[dev] --no-deps

      - name: Generate coverage report
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          pytest -sv -m "not plot"

  Optional-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          use-mamba: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment-optional-packages.yml
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true

      - name: Install dev-dependencies
        run: |
            pip install .[dev] --no-deps

      - name: Generate coverage report
        shell: bash -el {0}
        run: |
          conda activate test
          conda info
          conda list
          conda config --show-sources
          conda config --show
          pytest -sv

  Trigger-Test-Notebook:
    needs: Optional-packages
    runs-on: ubuntu-latest
    steps:
      - name: Call test-jupyter-notebooks workflow
        uses: pyramids/.github/workflows/test-jupyter-notebooks.yml
        with:
          environment-path: test
