name: test-jupyter-notebooks

on:
  workflow_call:
    workflows:
      - conda-deployment
    types:
      - completed

jobs:
  Test-Jupyter-Notebooks:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          use-mamba: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment-optional-packages.yml
          activate-environment: test
          python-version: 3.12
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true

      - name: Install dev-dependencies
        run: |
          pip install .[dev] --no-deps

      - name: Test Jupyter Notebook
        shell: bash -el {0}
        run: |
          conda activate test
          pip install -e .
          pytest --nbval -k ".ipynb"
