name: Main-package-conda
on: [push, pull_request]
jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          #use-mamba: true
          auto-update-conda: false
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            python -m pip install -r requirements-dev.txt
            python setup.py install

      - name: Generate coverage report
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          pytest -sv -m "not plot"
